enthub/ent/urls.py
from django.urls import path, re_path

from . import views

app_name = 'ent'

#urlpatterns = [
    #path('', views.article_list, name='home'),
    #url(r'^comment/$', views.comment, name='comment'),
    #path(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    #path(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    #path(?P<id>\d+)/favourite_post/$', views.favourite_post, name="favourite_post"),
    #path((?P<id>\d+)/(?P<slug>[\w-]+)/$', views.article_details, name="article_details"),
    #path('post_create/$', views.post_create, name="post_create"),
    #path('edit_profile/$', views.edit_profile, name="edit_profile"),
#]

urlpatterns = [
    path('', views.article_list, name='article_list'),
    re_path(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.article_details, name="article_details"),
    re_path(r'(?P<id>\d+)/favourite_post/$', views.favourite_post, name="favourite_post"),

]

enthub/enthub/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from ent import views as yct_views
from contact import views as contact_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('ent.urls', namespace="ent")),
    #path('', include('users.urls', namespace="users")),
    path('contact/', contact_views.contact_page, name="contact_page"),
    path('about/', yct_views.about, name="about"),
    
    path('login/', yct_views.user_login, name="user_login"),
    path('post_create/', yct_views.post_create, name="post_create"),
    path('activate/<uidb64>/<token>', yct_views.ActivateAccountView.as_view(), name="activate"),
    path('logout/', yct_views.user_logout, name="user_logout"),
    path('signup/', yct_views.signup_view, name="signup_view"),
    
    path('like/', yct_views.like_post, name="like_post"),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

enthub/ent/models.py
from __future__ import unicode_literals

from django.db import models
import uuid
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.fields import BLANK_CHOICE_DASH
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
#from ckeditor.fields import RichTextField


# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")

class Article(models.Model):
    objects = models.Manager()      #Our default Manager
    published = PublishedManager()  #Our Custom Model Manager

    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )

    DURATION_CHOICES = (
        (7,'1 Week'),
        (14,'2 Weeks'),
        (28,'3 Weeks'),
        (31,'1 Month'),
        (366,'1 Year'),

    )

    CATEGORY_CHOICES = (
        ('Agriculture & Food','Agriculture & Food'),
        ('Animals & Pets','Animals & Pets'),
        ('Babies & Kids','Babies & Kids'),
        ('Commercial Equipment & Tool','Commercial Equipment & Tool'),
        ('Electronics','Electronics'),
        ('Fashion','Fashion'),
        ('Health & Beauty','Health & Beauty'),
        ('Home, Furniture & Appliances','Home, Furniture & Appliances'),
        ('Mobile Phones & Tablets','Mobile Phones & Tablets'),
        ('Property','Property'),
        ('Repair & Construction','Repair & Construction'),
        ('Seeking Work - CVs','Seeking Work - CVs'),
        ('Services','Services'),
        ('Sport, Art & Outdoors','Sport, Art & Outdoors'),
        ('Vehicles','Vehicles'),
        
    )

    reference           =       models.UUIDField( editable=False, unique=True)
    title               =       models.CharField(max_length=200)
    slug                =       models.SlugField(max_length=200)
    status              =       models.CharField(max_length=10, choices=BLANK_CHOICE_DASH + list(STATUS_CHOICES))
    
    author              =       models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    amount              =       models.PositiveIntegerField(default=0)
    category            =       models.CharField( max_length=100, choices=BLANK_CHOICE_DASH + list(CATEGORY_CHOICES))
    description         =       models.TextField()
    video               =       models.FileField(blank=True, null=True)
    image               =       models.ImageField(blank=True, null=True)
    bodysnippet         =       models.TextField(default='', blank=True, null=True)
    body                =       RichTextUploadingField(default='', blank=True, null=True)
    link1                =       models.TextField(default='', blank=True, null=True)
    video2               =       models.FileField(blank=True, null=True)
    image2              =       models.ImageField(blank=True, null=True)
    body1               =       RichTextUploadingField(default='', blank=True, null=True)
    link2                =       models.TextField(default='', blank=True, null=True)
    video3               =       models.FileField(blank=True, null=True)
    image3              =       models.ImageField(blank=True, null=True)
    body2               =       RichTextUploadingField(default='', blank=True, null=True)
    link3                =       models.TextField(default='', blank=True, null=True)
    video4               =       models.FileField(blank=True, null=True)
    image4              =       models.ImageField(blank=True, null=True)
    body3               =       RichTextUploadingField(default='', blank=True, null=True)
    link4                =       models.TextField(default='', blank=True, null=True)
    video5               =       models.FileField(blank=True, null=True)
    image5              =       models.ImageField(blank=True, null=True)
    body4               =       RichTextUploadingField(default='', blank=True, null=True)
    link5                =       models.TextField(default='', blank=True, null=True)
    video6               =       models.FileField(blank=True, null=True)
    image6              =       models.ImageField(blank=True, null=True)
    body5               =       RichTextUploadingField(default='', blank=True, null=True)
    link6                =       models.TextField(default='', blank=True, null=True)
    video7               =       models.FileField(blank=True, null=True)
    image7              =       models.ImageField(blank=True, null=True)
    body6               =       RichTextUploadingField(default='', blank=True, null=True)
    link7                =       models.TextField(default='', blank=True, null=True)
    video8               =       models.FileField(blank=True, null=True)
    image8              =       models.ImageField(blank=True, null=True)
    body7               =       RichTextUploadingField(default='', blank=True, null=True)
    link8                =       models.TextField(default='', blank=True, null=True)
    video9               =       models.FileField(blank=True, null=True)
    image9              =       models.ImageField(blank=True, null=True)
    body8               =       RichTextUploadingField(default='', blank=True, null=True)
    link9                =       models.TextField(default='', blank=True, null=True)
    video10               =       models.FileField(blank=True, null=True)
    image10              =       models.ImageField(blank=True, null=True)
    body9               =       RichTextUploadingField(default='', blank=True, null=True)
    link10                =       models.TextField(default='', blank=True, null=True)
    video11               =       models.FileField(blank=True, null=True)
    image11             =       models.ImageField(blank=True, null=True)
    body10               =       RichTextUploadingField(default='', blank=True, null=True)
    link11                =       models.TextField(default='', blank=True, null=True)
    video12               =       models.FileField(blank=True, null=True)
    image12             =       models.ImageField(blank=True, null=True)
    link12                =       models.TextField(default='', blank=True, null=True)
    view_count          =       models.PositiveIntegerField(default=0)
    duration          =       models.PositiveIntegerField(default=10, choices=BLANK_CHOICE_DASH + list(DURATION_CHOICES))
    likes               =       models.ManyToManyField(User, related_name='likes', blank=True)
    created             =       models.DateTimeField(auto_now_add=True)
    updated             =       models.DateTimeField(auto_now=True)
    restrict_comment    =       models.BooleanField(default=False)
    favourite           =       models.ManyToManyField(User, related_name='favourite', blank=True)
    #reference           =       models.CharField(max_length=300, unique=True, editable=False, default=uuid.uuid4)
    



    def __str__(self):
        return str(self.post.id)


    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def snippet(self):
        return self.bodysnippet[:200] + "..."

    def total_likes(self):
        return self.likes.count()

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.image2.delete()
        self.image3.delete()
        super().delete(*args, **kwargs)


    def get_absolute_url(self):
        return reverse("ent:article_details", args=[self.id, self.slug])


@receiver(pre_save, sender=Article)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug




class AdvertImages(models.Model):
    company_name    =       models.CharField(max_length=200)
    amount          =       models.PositiveIntegerField(default=0)
    duration        =       models.CharField(max_length=10)
    bodysnippet     =       models.TextField(default='', blank=True, null=True)
    body            =       RichTextUploadingField(default='', blank=True, null=True)
    pic             =       models.ImageField(upload_to='images/', blank=True, null=True)
    vid             =       models.FileField(blank=True, null=True)


    def __str__(self):
        return str(self.company_name.id)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.company_name

    def snippet(self):
        return self.bodysnippet[:100] + "..."



class Reference(models.Model):
    user_reference_number      =       models.CharField(max_length=200)



    def __str__(self):
        returnnstr(self.reference)



class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', on_delete=models.CASCADE, null=True, related_name="replies")
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)


class Images(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/', blank=True, null=True)

    def __str__(self):
        return str(self.post.id)

enthub/ent/forms.py
from django import forms
from . import models

#class CommentArticle(forms.ModelForm):
	#class Meta:
		#model = models.Article
		#fields = ['title', 'body', 'slug', 'thumb']
from .models import Article, Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'category',
            'title',
            'description',
            'duration',
            'amount',
            'image',
            'image2',
            'image3',
            'status',
        )

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            'title',
            'body',
            'status',
            'restrict_comment',
        )


class UserLoginForm(forms.Form):
    username = forms.CharField(label="", widget= forms.TextInput(attrs = {'placeholder':'Username'}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs = {'placeholder':'Password'}))


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="", widget = forms.PasswordInput(attrs = {'id': 'pass1','class': 'input100', 'placeholder':'Enter Password Here...'}))
    confirm_password = forms.CharField(label="",  widget = forms.PasswordInput(attrs = {'id': 'pass2', 'class': 'input100'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            )
    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Password Mismatch")
        return email


class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

#class ProfileEditForm(forms.ModelForm):
#    class Meta:
#        model = Profile
#        exclude = ('user',)



class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Comment here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

enthub/ent/templates/ent/about.html
{% extends 'ent/base.html' %}

{% block title %}About Us! | {{ block.super }}{% endblock %}


{% block style %}
  <style>
  #fix {
    position: fixed;
    bottom: 0px;
    width: 100%;
  }
  </style>


{% endblock %}



{% block jumbotron %}
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
    
          <h1 id='grw' class="display-3">About Us!</h1>

          <div class="article">
                                       <p>we are located at bla bla bla, bla bla bla</p>
                                       <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
                            </div>

     </main>
{% endblock %}

enthub/ent/templates/ent/activate.html
{% autoescape off %}

Hi {{ user.username }}
Please click the link below to verify your account

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

enthub/ent/templates/ent/activate_failed.html
{% extends 'ent/base.html' %}

{% block container %}
<h3> 
	Something went wrong, please re requestthe activation link
</h3>

{% endblock %}

enthub/ent/templates/ent/article_list.html
{% extends 'ent/base.html' %}

{% block title %}Home | {{ block.super }}{% endblock %}



{% block jumbotron %}
    <section class="top-container">
      
        {% if b.image %}
        <header class="showcase" style="background: url({{ b.image.url }})">
        {% endif %}
          <h1>{{ b.title|upper }}</h1>
          <p>{{ b.bodysnippet|linebreaks }}</p>
          <a href="{{ b.get_absolute_url }}" class="btn">Read More</a>
        </header>
        <div class="top-box top-box-a" style="background: url({{ .image.url }})">
          {% if request.user.is_authenticated %}
          <h4>{{ user.username|capfirst }}</h4>
          {% else %}
             <h4>PLACE YOUR ADS HERE</h4>
          {% endif %}
          <p class="price">NGN20,000/mo</p>
          <a href="" class="btn">Advertise Now</a>
        </div>
        <div class="top-box top-box-b" style="background: url({{ .image.url }})">
          <h4>PLACE YOUR ADS HERE</h4>
          <p class="price">NGN10,000/we</p>
          <a href="" class="btn">Advertise Now</a>
        </div>
      </section>

{% endblock %}




{% block post %}



    <section class="boxes center">
      {% for p in d %}
        <div class="box">
          
          {% if p.image %}
          <a href="{{ p.get_absolute_url }}">
            <img src="{{ p.image.url }}" alt="Image Not Found" >
          </a>    
          {% endif %}
          <h3 ><a href="{{ p.get_absolute_url }}">{{ p.title|upper }}</a></h3>
          <p> {{ p.snippet|safe }} </p>
        </div>
        {% endfor %}
        </section>

<!--<ul class="pagination">
  {% if posts.has_previous %}
    <li class="page-item">
      <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
    </li>
  {% endif %}

  {% for p in page_range %}
    {% if posts.number == p %}
      <li class="page-item active">
        <a href="?page={{ p }}" class="page-link">{{ p }}</a>
      </li>
    {% else %}
      <li class="page-item">
        <a href="?page={{ p }}" class="page-link">{{ p }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if posts.has_next %}
    <li class="page-item">
      <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
    </li>
  {% endif %}
</ul> -->


{% endblock %}



{% block content %}

<!-- Info Section -->
      <section class="info">
          {% if j.image %}
              <img src="{{ j.image.url }}" alt="Image Not Found">
          {% endif %}
          <div>
              <h2> {{ j.title|upper }} </h2>
              <p> {{ j.snippet|safe }} </p>

              <!-- <p id="fix"><small>Posted by: {{ i.author|capfirst }} | {{ i.created }}</small></p> -->
              <a class="btn" href="{{ j.get_absolute_url }}">Learn More</a>
          </div>
      </section>


{% endblock %}


{% block main %}
<section class="portfolio">

    {% for l in g %}
          {% if l.image %}
          <a href="{{ l.get_absolute_url }}">
                <img src="{{ l.image.url }}" alt="Image Not Found">
          </a>
          {% endif %}
          
    {% endfor %}
  </section>

{% endblock %}

enthub/ent/templates/ent/footer.html
<footer id='fix'>
	<p>YCT &copy; 2020</p>
</footer>

enthub/ent/templates/ent/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="{% url 'like_post' %}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-danger">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
  {% endif %}
</form>
{% endif %}

enthub/ent/templates/ent/navbar.html
{% load staticfiles %}


<nav>
    <div class="lines">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>
    <div class="logo">
        <img src="{% static 'img/yctmarket.png' %}" alt="Image Not Found">
    </div>
    

    <ul class="nav-links">
        {% url 'ent:article_list' as article_list %}
        {% url 'about' as about %}
        {% url 'post_create' as post_create %}
        {% url 'contact_page' as contact_page %}
        <li >
            <a class="{% if request.path == article_list %}active{% endif %}" href="{% url 'ent:article_list' %}">Market</a>
        </li>
        
        <li >
            <a class="{% if request.path == about %}active{% endif %}" href="{% url 'about' %}">About</a>
        </li>

        <li >
            <a class="{% if request.path == post_create %}active{% endif %}" href="{% url 'post_create' %}">Post</a>
        </li>


        <li >
            <a class="{% if request.path == contact_page %}active{% endif %}" href="{% url 'contact_page' %}">Contact</a>
        </li>

        {% if not request.user.is_authenticated %}

            <li >
            <a class="{% if request.path == user_login  %}active{% endif %}" href="{% url 'user_login' %}" >login</a>
            </li>
                <li >
                <a class="{% if request.path == signup_view %}active{% endif %}" href="{% url 'signup_view' %}">Sign-Up</a>
            </li>


        {% else %}
            
              <li>
              <a  href="#">Profile</a>
          </li>
          <li>
              <a  href="{% url 'user_logout' %}">Logout</a>
          </li>
                
        {% endif %}
        
      
    </ul>


</nav>

enthub/ent/templates/ent/post_create.html
{% extends 'ent/base.html' %}
{% load crispy_forms_tags %}


{% block container %}
     <div class="limiter">
            <div class="container-login100">
              <div class="wrap-login100">
                                      

              {% if form %}

                <form method="post" enctype="multipart/form-data" action="{% url 'post_create' %}" class="login100-form validate-form p-l-55 p-r-55 p-t-178">
                  {% csrf_token %}
                  <span class="login100-form-title">
                    Upload Product
                  </span>

                  {{ form.category.label }}


                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.category }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.category.errors }}</div>
                  {% endif %}

                  {{ form.title.label }}

                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.title }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.title.errors }}</div>
                  {% endif %}

                    {{ form.description.label }}
                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.description }}
                    
                    <span class="focus-input100"></span>
                  </div>

                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.description.errors }}</div>
                  {% endif %}


                   {{ form.amount.label }}
                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.amount }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.amount.errors }}</div>
                  {% endif %}


                  {{ form.duration.label }}
                  <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.duration }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.duration.errors }}</div>
                  {% endif %}

                   {{ form.image.label }}
                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.image }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.image.errors }}</div>
                  {% endif %}

                  {{ form.image2.label }}
                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.image2 }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.image2.errors }}</div>
                  {% endif %}


                  {{ form.image3.label }}
                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.image3 }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.image3.errors }}</div>
                  {% endif %}


                    {{ form.status.label }}
                   <div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
                    {{ form.status }}
                    
                    <span class="focus-input100"></span>
                  </div>
                  {% if form.errors %}
                  <div class="wrap-input100 validate-input m-b-16">{{ form.status.errors }}</div>
                  {% endif %}
                  <br>
                  <br>

                  <div class="container-login100-form-btn">
                    <button id="submitt" class="login100-form-btn">
                      Upload
                    </button>
                  </div>

                  {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                  {% endif %}

                  <br>
                  <br>
                  <br>
                </form>
              </div>
            </div>
          </div>

										    
										  </form>
                                      {% endif %}
                            </div>
                    </div>
                </div>
              
                     
          </div>

          <hr>

        </div> <!-- /container -->
{% endblock %}


{% block java %}
  <script>
        var inputs = document.querySelectorAll('input');
        var text_area = document.querySelector('#id_description');
        var category = document.querySelector('#id_category');
        var amount = document.querySelector('#id_amount');
        var duration = document.querySelector('#id_duration');
        var image = document.querySelector('#id_image');
        var image2 = document.querySelector('#id_image2');
        var image3 = document.querySelector('#id_image3');
        var status = document.querySelector('#id_status');
        var label = document.createElement('label');

        label.setAttribute('amount', 'Amount in naira')


        text_area.setAttribute('class', 'input100');
        amount.setAttribute('class', 'input100');
        amount.setAttribute('label', 'Amount in Naira');
        image.setAttribute('class', 'input100');
        image2.setAttribute('class', 'input100');
        image3.setAttribute('class', 'input100');
        category.setAttribute('class', 'input100');
        duration.setAttribute('class', 'input100');
        amount.setAttribute('class', 'input100');
        text_area.style.height = "50%";
        image.style.height = "10%";
        image2.style.height = "10%";
        image3.style.height = "10%";
        category.style.height = "10%";
        duration.style.height = "10%";
        text_area.required = true;


        for (var index = 0; index < inputs.length; ++index){
            
            inputs[1].setAttribute('class', 'input100');
            inputs[2].setAttribute('class', 'input100');
            inputs[4].setAttribute('class', 'input100');

            inputs[index].required = true;
            


        }

        var error = document.querySelector('li');
        error.style.color = red;

    </script>
    {% endblock %}